# Generated by Django 5.2.7 on 2025-11-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatstate',
            name='selected_student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
