# Generated by Django 5.2.7 on 2025-10-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        ('schoolApp', '0007_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='schoolApp.subject'),
        ),
    ]
