# Generated by Django 5.2.8 on 2025-11-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='enrollement_number',
            new_name='enrollement_no',
        ),
    ]
