# Generated by Django 5.2.8 on 2025-11-08 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_studentprofile_class_name'),
        ('schoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'ordering': ['-joining_date']},
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='aadhaar_doc',
            field=models.FileField(blank=True, null=True, upload_to='teacher_docs/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='class_teacher_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher', to='schoolApp.class'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='classes_handled',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='email',
            field=models.EmailField(default='xyz@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='experience_doc',
            field=models.FileField(blank=True, null=True, upload_to='teacher_docs/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='language_preference',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_profiles/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teacher_name',
            field=models.CharField(default='xyz', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='joining_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='staff_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='schoolApp.subject'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=10, null=True),
        ),
    ]
