# Generated by Django 5.2.8 on 2025-11-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_teacherprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='aadhaar_number',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='salary',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='age',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
