# Generated by Django 5.2.8 on 2025-11-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_remove_teacherprofile_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollement_no',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
