# Generated by Django 5.2.8 on 2025-11-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_alter_studentprofile_enrollement_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollement_no',
            field=models.CharField(blank=True, default=None, editable=False, max_length=20, unique=True),
        ),
    ]
