# Generated by Django 5.2.8 on 2025-11-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_alter_studentprofile_enrollement_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='enrollement_no',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='enrollment_no',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
