# Generated by Django 5.2.7 on 2025-10-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0002_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('audience_type', models.CharField(choices=[('All', 'All'), ('Parents', 'Parents'), ('Students', 'Students'), ('Teachers', 'Teachers')], max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
