# Generated by Django 5.2.8 on 2025-11-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0002_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='classrooms',
        ),
    ]
