# Generated by Django 5.2.8 on 2025-11-13 06:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0004_attendance_selected_class_alter_attendance_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('students', 'Students'), ('class', 'Class')], default='students', help_text='Select who this notice is for', max_length=20)),
                ('class_name', models.CharField(blank=True, help_text='Specify class if applicable (leave empty for all classes)', max_length=50, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('applicable_date', models.DateField(default=django.utils.timezone.now)),
                ('specific_students', models.TextField(blank=True, help_text='Comma-separated names or admission numbers if notice is for specific students', null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField()),
                ('posted_by', models.ForeignKey(default=None, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='notices_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
