# Generated by Django 5.2.8 on 2025-11-13 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_remove_studentprofile_enrollement_no_and_more'),
        ('schoolApp', '0005_noticemodel_delete_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='teacher',
        ),
        migrations.AddField(
            model_name='homework',
            name='Assigned_By_teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='Account.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.TextField(max_length=1025),
        ),
        migrations.AlterField(
            model_name='homework',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='assigned_homeworks_to', to='Account.studentprofile'),
        ),
        migrations.AlterField(
            model_name='noticemodel',
            name='target',
            field=models.CharField(choices=[('student', 'Student'), ('classes', 'classes'), ('Teachers', 'Teachers')], default='students', help_text='Select who this notice is for', max_length=20),
        ),
        migrations.AlterField(
            model_name='noticemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
