# Generated by Django 5.2.7 on 2025-10-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0007_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject']},
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='subject',
        ),
    ]
