# Generated by Django 5.2.7 on 2025-10-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0008_alter_subject_options_rename_name_subject_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='class_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='section_name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='grade_level',
        ),
        migrations.AddField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
