# Generated by Django 5.2.7 on 2025-10-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0009_rename_class_name_classroom_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('max_student', models.PositiveIntegerField(default=40)),
                ('classrooms', models.ManyToManyField(related_name='classes', to='schoolApp.classroom')),
                ('subjects', models.ManyToManyField(related_name='classes', to='schoolApp.subject')),
            ],
        ),
    ]
