# Generated by Django 5.2.7 on 2025-10-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0010_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='facilities',
            field=models.CharField(choices=[('blackboard', 'Blackboard'), ('whiteboard', 'Whiteboard'), ('projector', 'Projector'), ('smart_board', 'Smart Board'), ('digital_display', 'Digital Display')], default='blackboard', help_text='Type of board or teaching equipment available', max_length=20),
        ),
    ]
