# Generated by Django 5.2.7 on 2025-10-14 08:33

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0011_classroom_facilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='max_student',
            new_name='max_seats',
        ),
        migrations.AlterField(
            model_name='notice',
            name='audience_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('All', 'All'), ('Parents', 'Parents'), ('Students', 'Students'), ('Teachers', 'Teachers')], max_length=50),
        ),
    ]
