# Generated by Django 5.2.7 on 2025-10-15 09:15

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0012_rename_max_student_class_max_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='facilities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('blackboard', 'Blackboard'), ('whiteboard', 'Whiteboard'), ('projector', 'Projector'), ('smart_board', 'Smart Board'), ('digital_display', 'Digital Display')], default='blackboard', help_text='Type of board or teaching equipment available', max_length=225),
        ),
    ]
