# Generated by Django 5.2.7 on 2025-10-15 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0013_alter_classroom_facilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='classroom',
        ),
        migrations.AddField(
            model_name='homework',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='schoolApp.class'),
        ),
    ]
