# Generated by Django 5.2.7 on 2025-10-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0014_remove_homework_classroom_homework_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='name',
            new_name='class_name',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='name',
            new_name='class_room',
        ),
    ]
